default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: phpriorities

test:
  <<: *default
  database: phpriorities_test

production:
  <<: *default
  uri: <%= ENV['DATABASE_URL'] %>
